name: Simpan Pesan

on:
  workflow_dispatch:
    inputs:
      pesan:
        description: "Pesan yang dikirim dari website"
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Tambahkan pesan ke file
        run: |
          echo "${{ github.event.inputs.pesan }}" >> pesan.txt

      - name: Commit & Push
        run: |
          git config user.name "Birthday Bot"
          git config user.email "bot@example.com"
          git add pesan.txt
          git commit -m "Tambah pesan baru"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MYHB }}
